-- 코드를 입력하세요
SELECT A.MCDP_CD AS '진료과 코드', COUNT(APNT_NO) AS '5월예약건수'
FROM APPOINTMENT A 
WHERE A.APNT_YMD >= '2022-05-01' AND A.APNT_YMD <= '2022-05-31'
GROUP BY A.MCDP_CD
ORDER BY COUNT(APNT_NO) ASC, A.MCDP_CD ASC