-- 코드를 입력하세요
SELECT m.FLAVOR
FROM FIRST_HALF h
JOIN (
    SELECT i.FLAVOR 
    FROM ICECREAM_INFO i
    WHERE i.INGREDIENT_TYPE = 'fruit_based'
) m ON h.FLAVOR = m.FLAVOR
WHERE h.TOTAL_ORDER > 3000
ORDER BY h.TOTAL_ORDER DESC