-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' 
    AND H.START_DATE >= '2022-10-01'
    AND H.START_DATE <= '2022-10-31'
    -- GROUP BY H.CAR_ID 집계 목적이 아니기 때문에 그룹바이보다 DISTINCT 쓰는게 의도에 맞음
ORDER BY C.CAR_ID DESC